docs: adding big bang app-arch diagram and reorg of the repo to accom…
defenseunicorns/bigbang-architecture-diagrams pull request #2
Opened 2022-12-21 01:58 UTC by MxNxPx

if it makes sense to live here, would like to pull in an application architecture type diagram for big bang

2023-01-04 18:22 UTC, MxNxPx commented
adding @runyontr to get his thoughts as well

2023-01-04 18:49 UTC, RothAndrew commented
Can you pull the license change out into a separate PR? Other than that I don't have any objections to this. It looks to mostly provide an alternative style of diagram which, while harder to read, is very likely more technically accurate.

2023-01-04 18:51 UTC, RothAndrew commented
The main question is whether we want to maintain both styles or pick one and delete the other.

I have no horse in this race so I'm fine with the C4 stuff going away if it means better maintainability and the other style has more value.

2023-01-04 18:55 UTC, RothAndrew submitted a review, later dismissed
see above comments

2023-01-04 21:03 UTC, MxNxPx commented
> Can you pull the license change out into a separate PR? Other than that I don't have any objections to this. It looks to mostly provide an alternative style of diagram which, while harder to read, is very likely more technically accurate.

good catch, overwriting the LICENSE was my oopsie.  reverting that back to the last commit.

2023-01-04 21:08 UTC, MxNxPx commented
> The main question is whether we want to maintain both styles or pick one and delete the other.
> 
> I have no horse in this race so I'm fine with the C4 stuff going away if it means better maintainability and the other style has more value.

i feel like both are useful points of view on the big bang architecture.  but if splitting the repo up in the PR proposed manner breaks some other documentation links or perhaps is not very useful, i am good with retracting the PR and seeing if it makes sense for the new diagram to have a different home.

@RothAndrew & @runyontr - what do you think?

2023-01-05 00:15 UTC, RothAndrew commented
I don't know if changing to the new folder structure will break any links, but if it does it won't be the end of the world for people to just update to the new location.

2023-01-05 00:21 UTC, RothAndrew requested changes

2023-01-05 00:21 UTC, RothAndrew commented on README.md
> +* [c4](./c4)
```suggestion
* [Simple but visually appealing](./c4) -- Uses the [C4 model](https://c4model.com/)
```

2023-01-05 00:21 UTC, RothAndrew commented on README.md
> +* [app-arch](./app-arch)
```suggestion
* [Technical](./app-arch) -- Uses [d2](https://github.com/terrastruct/d2)
```

2023-01-05 19:21 UTC, MxNxPx commented
@RothAndrew - I like your suggested changes so I went ahead and committed them to the branch.
Let me know if there is anything else we may want to change or review before merging or dropping the PR.

2023-01-05 19:21 UTC, RothAndrew approved these changes

2023-02-23 23:00 UTC, RothAndrew commented
@MxNxPx is this ready to merge?

2023-06-02 21:51 UTC, RothAndrew commented
@MxNxPx bump

2023-06-07 22:21 UTC, RothAndrew commented
Closing as abandoned

2023-06-07 22:21 UTC, closed without merging